name: test_aoshal
version: v7.4.3                                    # <必选项> 组件版本号
description: YoC helloworld SDK
type: solution

hw_info:

sdk_chip:
  - sdk_chip_pangu: v7.4.3

depends:                                       # 该组件依赖其他的组件
  - rhino: v7.4.3 
  - drivers: v7.4.3 
  - kv: v7.4.3 
  - at: v7.4.3
  - sdk_chip_pangu: v7.4.3

# 编译参数
build_config:
  include:
    - app/include

  ldflag: -Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024

# 源文件
source_file:
  - app/src/app_main.c
  - app/src/init.c
  - app/src/hal_test/*.c

def_config:
  # CONFIG_SYSTEM_SECURE: 1
  CONFIG_INIT_TASK_STACK_SIZE: 2048
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_CLI: 1
  CONFIG_DEBUG: 1
  CONFIG_PARAM_NOT_CHECK: 1
