mtb_version: 1
chip: cb2201          # cb2201 / cb6501
diff:
  fota_version: 0
  ram_buf: 50         #DEC     KB   ( max ram need)
  flash_buf: 4        #DEC     KB   ( buffer size)
  flash_sector: 512   #DEC     byte ( flash sector)
  diff_mode: 010      #BIN
flash:
  base_address: 0x10000000       # the base address of flash
  run_base_address: 0x10000000   # the run address, maybe sdram address
  sector: 512                   # Bytes
  size: 262144                  # Bytes, $(sector count) * sector
partitions:
  - { name: imtb,    address: 0x10000000, size: 0x001000 }
  - { name: tee,     address: 0x10001000, size: 0x005000, update: DIFF, verify: true }
  - { name: boot,    address: 0x10006000, size: 0x006000, verify: true }
  - { name: prim,    address: 0x1000C000, size: 0x028000, update: DIFF, verify: true }
  - { name: misc,    address: 0x10034000, size: 0x00AA00 }
  - { name: kv,      address: 0x1003EA00, size: 0x000C00 }
  - { name: lpm,     address: 0x1003F600, size: 0x000200 }
  - { name: otp,     address: 0x4003F800, size: 0x000800, file: dev_kp }
