name: mesh_switch_node_demo
version: v7.4.3
description: YoC MESH SDK
type: solution
solution:
  board_name: phy6220_evb
  ld_script: ""
# toolchain_prefix: csky-abiv2-elf
# cpu_name: CK802EF
# vendor_name: csky
# chip_name: 'phy6220_evb'
# ld_script: configs/gcc_eflash.ld.S
depends:
  - drv_light: v7.4.3
  - cli: v7.4.3
  - ble_mesh: v7.4.3
  # Chip SDK
  - sdk_chip_phy6220: v7.4.3
# board components
# 编译参数
build_config:
  include:
    - app/include
    - app/src
  internal_include: ~
  cflag: -Os  -g
  cxxflag: -Os  -g
  asmflag: ""
  define: ~
  libs: ~
  libpath: ~
  ldflag: -Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024 -u jump_table_base ./misc/rom_ck802.elf.ck802sym
# 源文件
source_file:
  - app/src/*.c
  - app/src/init/*.c
yoc_version: ""
keywords: ~
author: ""
license: ""
defconfig:
  CONFIG_ARCH_INTERRUPTSTACK: 768
  CONFIG_BT_L2CAP_RX_MTU: 131
  CONFIG_BT_L2CAP_TX_MTU: 131
  CONFIG_BT_MESH_CFG_CLI: 1
  CONFIG_BT_MESH_GATT_PROXY: 1
  CONFIG_BT_MESH_HEALTH_CLI: 1
  CONFIG_BT_MESH_MODEL_GEN_ONOFF_CLI: 1
  CONFIG_BT_MESH_MODEL_VENDOR_SRV: 1
  CONFIG_BT_MESH_PB_GATT: 1
  CONFIG_BT_MESH_USE_SIG_MODEL: 1
  CONFIG_CLI_TASK_STACK_SIZE: 1024
  CONFIG_DEBUG: 1
  CONFIG_INIT_TASK_STACK_SIZE: 1536
  CONFIG_KERNEL_TIMER_STACK_SIZE: 1536
  RHINO_CONFIG_TIMER_MSG_NUM: 10
  MESH_DEBUG_TX: 1
  MESH_DEBUG_RX: 1
#  CONFIG_BT_DEBUG_LOG: 1
#  CONFIG_BT_MESH_MODEL_GEN_ONOFF_SRV: 1
#  CONFIG_BT_MESH_MODEL_GEN_LEVEL_SRV: 1
#  CONFIG_BT_MESH_MODEL_LIGHT_LIGHTNESS_SRV: 1
#  CONFIG_BT_MESH_MODEL_LIGHT_CTL_SRV: 1
#  CONFIG_BT_DEBUG_LOG: 1
link_config:
  path: ~
  library: ~