type: solution
name: test_wifiprovisioning
version: v7.4.3
description: wifi provisioning test
hw_info:                              #用户修改为对应board和chip
  cpu_id: cpu0
  board_name: w800_evb
  ld_script: ""

sdk_chip:
  - sdk_chip_w800: v7.4.3
depends:
  - sdk_chip_w800: v7.4.3
  - wifi_provisioning: v7.4.3

def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_CLI: 1
  CONFIG_DEBUG: 1
  CONFIG_KERNEL_RHINO: 1
  CLI_CONFIG_STACK_SIZE: 4096
  CONFIG_KV_SMART: 1
  CONFIG_IRQ_VECTOR_SIZE: 256


build_config:
  ldflag: '-Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024'
  include:
    - app/include
source_file:
  - app/src/main.c
  - app/src/yunit_test_main.c
  - app/src/yunit.c
  - app/src/init/*.c
  - app/src/api_test.c
  - app/src/wifi_provising/*.c
