name: test_csi2
version: v7.4.3
description: csi solution
type: solution
hw_info:
  cpu_id: cpu0
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ch2601_evb
  ld_script: ""
  flash_program: ""
#cpu_name: ""
#vendor_name: ""
#chip_name: ""
#ld_script: gcc_eflash.ld
#flash_program: ""
#sdk_chip:
#  - sdk_chip_ch2601: v7.4.3
depends:
  - sdk_chip_ch2601: v7.4.3
# 编译参数
build_config:
  include:
    - app/include
    - app/include/csi/atserver
    - app/include/csi/common
    - app/include/csi/driver
  internal_include: ~
  cflag: -O0   -Wall
  cxxflag: -O0   -Wall
  asmflag: ""
  define: ~
  libs: ~
  libpath: ~
# 源文件
source_file:
  - app/src/app_main.c
  - app/src/driver_tests_main.c
  - app/src/init/*.c
  - app/src/csi/common/*.c
  - app/src/csi/atserver/*.c
  - app/src/csi/driver/pinmux/*.c
  - app/src/csi/driver/pin/*.c
  - app/src/csi/driver/aes/*.c ? <CONFIG_AES>
  - app/src/csi/driver/rsa/*.c ? <CONFIG_RSA>
  - app/src/csi/driver/dma/*.c ? <CONFIG_DMA>
  - app/src/csi/driver/sha/*.c ? <CONFIG_SHA>
  - app/src/csi/driver/trng/*.c ? <CONFIG_TRNG>
  - app/src/csi/driver/wdt/*.c ? <CONFIG_WDT>
  - app/src/csi/driver/gpio/*.c ? <CONFIG_GPIO>
  - app/src/csi/driver/timer/*.c ? <CONFIG_TIMER>
  - app/src/csi/driver/iic/*.c ? <CONFIG_IIC>
  - app/src/csi/driver/spi/*.c ? <CONFIG_SPI>
  - app/src/csi/driver/mbox/*.c ? <CONFIG_MBOX>
  - app/src/csi/driver/uart/*.c ? <CONFIG_UART>
  - app/src/csi/driver/pwm/*.c ? <CONFIG_PWM>
  - app/src/csi/driver/tick/*.c ? <CONFIG_TICK>
  - app/src/csi/driver/i2s/*.c ? <CONFIG_I2S>
  - app/src/csi/driver/codec/*.c ? <CONFIG_CODEC>
  - app/src/csi/driver/intnest/*.c ? <CONFIG_INTNEST>
  - app/src/csi/driver/mbox/*.c ? <CONFIG_MBOX>
  - app/src/csi/driver/efuse/*.c ? <CONFIG_EFUSE>
  - app/src/csi/driver/adc/*.c ? <CONFIG_ADC>
  - app/src/csi/driver/spiflash/*.c ? <CONFIG_SPIFLASH>
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_CLI: 1
  CONFIG_CPU_E906: 1
  CONFIG_CSI_V2: 1
  CONFIG_DEBUG: 3
  CONFIG_DMA: 1
  CONFIG_INIT_TASK_STACK_SIZE: 2048
  CONFIG_SUPPORT_TSPEND: 1
  CONFIG_XIP: 1
#  CONFIG_TEE_CA: 1
#  CONFIG_SYSTEM_SECURE: 1
#  CONFIG_NUTTXMM_NONE: 1
#  CONFIG_KERNEL_NONE: 1
# CONFIG_AES: 1
# CONFIG_CRC: 1
# CONFIG_UART: 1
# CONFIG_ADC: 1
# CONFIG_CODEC: 1
# CONFIG_EFUSE: 1
# CONFIG_GPIO: 1
# CONFIG_I2S: 1
# CONFIG_IIC: 1
# CONFIG_INTNEST: 1
# CONFIG_MBOX: 1
# CONFIG_PWM: 1
# CONFIG_RSA: 1
#CONFIG_SHA: 1
# CONFIG_SPI: 1
# CONFIG_TICK: 1
# CONFIG_TIMER: 1
# CONFIG_TRNG: 1
# CONFIG_WDT: 1
# CONFIG_SPIFLASH: 1
keywords: ~
tag: ""
author:
  name: ""
license: ""
# CONFIG_DEBUG_MM: 1
##secure config##
