board_config:
	- {'name': 'I2S', 'idx': '0', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P0', 'pin_func': 'PA0_I2S0_SCLK'}
	- {'name': 'SPI', 'idx': '0', 'func': 'CS', 'port': 'PORTA', 'pin': 'P0', 'pin_func': 'PA0_SPI0_CS'}
	- {'name': 'UART', 'idx': '0', 'func': 'RX', 'port': 'PORTA', 'pin': 'P0', 'pin_func': 'PA0_UART0_RX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH0', 'port': 'PORTA', 'pin': 'P0', 'pin_func': 'PA0_PWM_CH0'}
	- {'name': 'ADC', 'idx': 0, 'func': 'VREFP', 'port': 'PORTA', 'pin': 'P0', 'pin_func': 'PA0_ADC_VREFP'}
	- {'name': 'I2S', 'idx': '0', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P1', 'pin_func': 'PA1_I2S0_WSCLK'}
	- {'name': 'SPI', 'idx': '0', 'func': 'SCK', 'port': 'PORTA', 'pin': 'P1', 'pin_func': 'PA1_SPI0_SCK'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P1', 'pin_func': 'PA1_UART0_TX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH1', 'port': 'PORTA', 'pin': 'P1', 'pin_func': 'PA1_PWM_CH1'}
	- {'name': 'ADC', 'idx': 0, 'func': 'VREFN', 'port': 'PORTA', 'pin': 'P1', 'pin_func': 'PA1_ADC_VREFN'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P2', 'pin_func': 'PA2_I2S1_SCLK'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P2', 'pin_func': 'PA2_I2C0_SCL'}
	- {'name': 'SPI', 'idx': '1', 'func': 'CS', 'port': 'PORTA', 'pin': 'P2', 'pin_func': 'PA2_SPI1_CS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH2', 'port': 'PORTA', 'pin': 'P2', 'pin_func': 'PA2_PWM_CH2'}
	- {'name': 'I2S', 'idx': '1', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P3', 'pin_func': 'PA3_I2S1_WSCLK'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P3', 'pin_func': 'PA3_I2C0_SDA'}
	- {'name': 'SPI', 'idx': '1', 'func': 'SCK', 'port': 'PORTA', 'pin': 'P3', 'pin_func': 'PA3_SPI1_SCK'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH3', 'port': 'PORTA', 'pin': 'P3', 'pin_func': 'PA3_PWM_CH3'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A1', 'port': 'PORTA', 'pin': 'P3', 'pin_func': 'PA3_ADC_A1'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P4', 'pin_func': 'PA4_I2S0_SDA'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P4', 'pin_func': 'PA4_SPI0_MOSI'}
	- {'name': 'UART', 'idx': '1', 'func': 'CTS', 'port': 'PORTA', 'pin': 'P4', 'pin_func': 'PA4_UART1_CTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH4', 'port': 'PORTA', 'pin': 'P4', 'pin_func': 'PA4_PWM_CH4'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A2', 'port': 'PORTA', 'pin': 'P4', 'pin_func': 'PA4_ADC_A2'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P5', 'pin_func': 'PA5_I2S1_SDA'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P5', 'pin_func': 'PA5_SPI0_MISO'}
	- {'name': 'UART', 'idx': '1', 'func': 'RTS', 'port': 'PORTA', 'pin': 'P5', 'pin_func': 'PA5_UART1_RTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH5', 'port': 'PORTA', 'pin': 'P5', 'pin_func': 'PA5_PWM_CH5'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A3', 'port': 'PORTA', 'pin': 'P5', 'pin_func': 'PA5_ADC_A3'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P6', 'pin_func': 'PA6_I2S0_SCLK'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P6', 'pin_func': 'PA6_UART0_TX'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P6', 'pin_func': 'PA6_SPI1_MOSI'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH6', 'port': 'PORTA', 'pin': 'P6', 'pin_func': 'PA6_PWM_CH6'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A4', 'port': 'PORTA', 'pin': 'P6', 'pin_func': 'PA6_ADC_A4'}
	- {'name': 'I2S', 'idx': '0', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P7', 'pin_func': 'PA7_I2S0_WSCLK'}
	- {'name': 'PWMR', 'idx': 0, 'func': 'OUT', 'port': 'PORTA', 'pin': 'P7', 'pin_func': 'PA7_PWMR_OUT'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P7', 'pin_func': 'PA7_SPI1_MISO'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH7', 'port': 'PORTA', 'pin': 'P7', 'pin_func': 'PA7_PWM_CH7'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A5', 'port': 'PORTA', 'pin': 'P7', 'pin_func': 'PA7_ADC_A5'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P8', 'pin_func': 'PA8_I2S0_SDA'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P8', 'pin_func': 'PA8_I2C0_SCL'}
	- {'name': 'UART', 'idx': '0', 'func': 'RX', 'port': 'PORTA', 'pin': 'P8', 'pin_func': 'PA8_UART0_RX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH8', 'port': 'PORTA', 'pin': 'P8', 'pin_func': 'PA8_PWM_CH8'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A6', 'port': 'PORTA', 'pin': 'P8', 'pin_func': 'PA8_ADC_A6'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P9', 'pin_func': 'PA9_I2S1_SDA'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P9', 'pin_func': 'PA9_I2C0_SDA'}
	- {'name': 'PWMR', 'idx': 0, 'func': 'OUT', 'port': 'PORTA', 'pin': 'P9', 'pin_func': 'PA9_PWMR_OUT'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH9', 'port': 'PORTA', 'pin': 'P9', 'pin_func': 'PA9_PWM_CH9'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A7', 'port': 'PORTA', 'pin': 'P9', 'pin_func': 'PA9_ADC_A7'}
	- {'name': 'I2S', 'idx': 0, 'func': 'MCLK', 'port': 'PORTA', 'pin': 'P10', 'pin_func': 'PA10_I2S_MCLK'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P10', 'pin_func': 'PA10_UART0_TX'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P10', 'pin_func': 'PA10_SPI1_MOSI'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P10', 'pin_func': 'PA10_SPI1_MISO'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A8', 'port': 'PORTA', 'pin': 'P10', 'pin_func': 'PA10_ADC_A8'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P15', 'pin_func': 'PA15_I2C0_SCL'}
	- {'name': 'SPI', 'idx': '0', 'func': 'CS', 'port': 'PORTA', 'pin': 'P15', 'pin_func': 'PA15_SPI0_CS'}
	- {'name': 'PWMR', 'idx': 0, 'func': 'OUT', 'port': 'PORTA', 'pin': 'P15', 'pin_func': 'PA15_PWMR_OUT'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH4', 'port': 'PORTA', 'pin': 'P15', 'pin_func': 'PA15_PWM_CH4'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A9', 'port': 'PORTA', 'pin': 'P15', 'pin_func': 'PA15_ADC_A9'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P16', 'pin_func': 'PA16_I2C0_SDA'}
	- {'name': 'SPI', 'idx': '0', 'func': 'SCK', 'port': 'PORTA', 'pin': 'P16', 'pin_func': 'PA16_SPI0_SCK'}
	- {'name': 'UART', 'idx': '1', 'func': 'TX', 'port': 'PORTA', 'pin': 'P16', 'pin_func': 'PA16_UART1_TX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH5', 'port': 'PORTA', 'pin': 'P16', 'pin_func': 'PA16_PWM_CH5'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A10', 'port': 'PORTA', 'pin': 'P16', 'pin_func': 'PA16_ADC_A10'}
	- {'name': 'UART', 'idx': '0', 'func': 'RX', 'port': 'PORTA', 'pin': 'P17', 'pin_func': 'PA17_UART0_RX'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P17', 'pin_func': 'PA17_SPI0_MOSI'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P17', 'pin_func': 'PA17_I2S0_SCLK'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH10', 'port': 'PORTA', 'pin': 'P17', 'pin_func': 'PA17_PWM_CH10'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A11', 'port': 'PORTA', 'pin': 'P17', 'pin_func': 'PA17_ADC_A11'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P18', 'pin_func': 'PA18_UART0_TX'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P18', 'pin_func': 'PA18_SPI0_MISO'}
	- {'name': 'I2S', 'idx': '0', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P18', 'pin_func': 'PA18_I2S0_WSCLK'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH11', 'port': 'PORTA', 'pin': 'P18', 'pin_func': 'PA18_PWM_CH11'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A12', 'port': 'PORTA', 'pin': 'P18', 'pin_func': 'PA18_ADC_A12'}
	- {'name': 'JTAG', 'idx': 0, 'func': 'TMS', 'port': 'PORTA', 'pin': 'P19', 'pin_func': 'PA19_JTAG_TMS'}
	- {'name': 'UART', 'idx': '1', 'func': 'RX', 'port': 'PORTA', 'pin': 'P19', 'pin_func': 'PA19_UART1_RX'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P19', 'pin_func': 'PA19_I2S1_SCLK'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P19', 'pin_func': 'PA19_I2C0_SCL'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A13', 'port': 'PORTA', 'pin': 'P19', 'pin_func': 'PA19_ADC_A13'}
	- {'name': 'JTAG', 'idx': 0, 'func': 'TCK', 'port': 'PORTA', 'pin': 'P20', 'pin_func': 'PA20_JTAG_TCK'}
	- {'name': 'UART', 'idx': '1', 'func': 'TX', 'port': 'PORTA', 'pin': 'P20', 'pin_func': 'PA20_UART1_TX'}
	- {'name': 'I2S', 'idx': '1', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P20', 'pin_func': 'PA20_I2S1_WSCLK'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P20', 'pin_func': 'PA20_I2C0_SDA'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A14', 'port': 'PORTA', 'pin': 'P20', 'pin_func': 'PA20_ADC_A14'}
	- {'name': 'UART', 'idx': '0', 'func': 'CTS', 'port': 'PORTA', 'pin': 'P21', 'pin_func': 'PA21_UART0_CTS'}
	- {'name': 'UART', 'idx': '1', 'func': 'CTS', 'port': 'PORTA', 'pin': 'P21', 'pin_func': 'PA21_UART1_CTS'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P21', 'pin_func': 'PA21_I2S0_SDA'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P21', 'pin_func': 'PA21_I2C0_SCL'}
	- {'name': 'ADC', 'idx': 0, 'func': 'A15', 'port': 'PORTA', 'pin': 'P21', 'pin_func': 'PA21_ADC_A15'}
	- {'name': 'UART', 'idx': '0', 'func': 'RTS', 'port': 'PORTA', 'pin': 'P22', 'pin_func': 'PA22_UART0_RTS'}
	- {'name': 'UART', 'idx': '1', 'func': 'RTS', 'port': 'PORTA', 'pin': 'P22', 'pin_func': 'PA22_UART1_RTS'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P22', 'pin_func': 'PA22_I2S1_SDA'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P22', 'pin_func': 'PA22_I2C0_SDA'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SCL', 'port': 'PORTA', 'pin': 'P23', 'pin_func': 'PA23_I2C0_SCL'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P23', 'pin_func': 'PA23_UART0_TX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH0', 'port': 'PORTA', 'pin': 'P23', 'pin_func': 'PA23_PWM_CH0'}
	- {'name': 'SPI', 'idx': '0', 'func': 'CS', 'port': 'PORTA', 'pin': 'P23', 'pin_func': 'PA23_SPI0_CS'}
	- {'name': 'I2C', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P24', 'pin_func': 'PA24_I2C0_SDA'}
	- {'name': 'UART', 'idx': '0', 'func': 'RX', 'port': 'PORTA', 'pin': 'P24', 'pin_func': 'PA24_UART0_RX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH1', 'port': 'PORTA', 'pin': 'P24', 'pin_func': 'PA24_PWM_CH1'}
	- {'name': 'SPI', 'idx': '0', 'func': 'SCK', 'port': 'PORTA', 'pin': 'P24', 'pin_func': 'PA24_SPI0_SCK'}
	- {'name': 'PWMR', 'idx': 0, 'func': 'OUT', 'port': 'PORTA', 'pin': 'P25', 'pin_func': 'PA25_PWMR_OUT'}
	- {'name': 'UART', 'idx': '0', 'func': 'CTS', 'port': 'PORTA', 'pin': 'P25', 'pin_func': 'PA25_UART0_CTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH2', 'port': 'PORTA', 'pin': 'P25', 'pin_func': 'PA25_PWM_CH2'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P25', 'pin_func': 'PA25_SPI0_MOSI'}
	- {'name': 'I2S', 'idx': 0, 'func': 'MCLK', 'port': 'PORTA', 'pin': 'P26', 'pin_func': 'PA26_I2S_MCLK'}
	- {'name': 'UART', 'idx': '0', 'func': 'RTS', 'port': 'PORTA', 'pin': 'P26', 'pin_func': 'PA26_UART0_RTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH3', 'port': 'PORTA', 'pin': 'P26', 'pin_func': 'PA26_PWM_CH3'}
	- {'name': 'SPI', 'idx': '0', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P26', 'pin_func': 'PA26_SPI0_MISO'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P27', 'pin_func': 'PA27_I2S0_SCLK'}
	- {'name': 'UART', 'idx': '1', 'func': 'RX', 'port': 'PORTA', 'pin': 'P27', 'pin_func': 'PA27_UART1_RX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH4', 'port': 'PORTA', 'pin': 'P27', 'pin_func': 'PA27_PWM_CH4'}
	- {'name': 'SPI', 'idx': '1', 'func': 'CS', 'port': 'PORTA', 'pin': 'P27', 'pin_func': 'PA27_SPI1_CS'}
	- {'name': 'I2S', 'idx': '0', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P28', 'pin_func': 'PA28_I2S0_WSCLK'}
	- {'name': 'UART', 'idx': '1', 'func': 'TX', 'port': 'PORTA', 'pin': 'P28', 'pin_func': 'PA28_UART1_TX'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH5', 'port': 'PORTA', 'pin': 'P28', 'pin_func': 'PA28_PWM_CH5'}
	- {'name': 'SPI', 'idx': '1', 'func': 'SCK', 'port': 'PORTA', 'pin': 'P28', 'pin_func': 'PA28_SPI1_SCK'}
	- {'name': 'I2S', 'idx': '1', 'func': 'SCLK', 'port': 'PORTA', 'pin': 'P29', 'pin_func': 'PA29_I2S1_SCLK'}
	- {'name': 'UART', 'idx': '1', 'func': 'CTS', 'port': 'PORTA', 'pin': 'P29', 'pin_func': 'PA29_UART1_CTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH6', 'port': 'PORTA', 'pin': 'P29', 'pin_func': 'PA29_PWM_CH6'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MOSI', 'port': 'PORTA', 'pin': 'P29', 'pin_func': 'PA29_SPI1_MOSI'}
	- {'name': 'I2S', 'idx': '1', 'func': 'WSCLK', 'port': 'PORTA', 'pin': 'P30', 'pin_func': 'PA30_I2S1_WSCLK'}
	- {'name': 'UART', 'idx': '1', 'func': 'RTS', 'port': 'PORTA', 'pin': 'P30', 'pin_func': 'PA30_UART1_RTS'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH7', 'port': 'PORTA', 'pin': 'P30', 'pin_func': 'PA30_PWM_CH7'}
	- {'name': 'SPI', 'idx': '1', 'func': 'MISO', 'port': 'PORTA', 'pin': 'P30', 'pin_func': 'PA30_SPI1_MISO'}
	- {'name': 'I2S', 'idx': '0', 'func': 'SDA', 'port': 'PORTA', 'pin': 'P31', 'pin_func': 'PA31_I2S0_SDA'}
	- {'name': 'PWMR', 'idx': 0, 'func': 'OUT', 'port': 'PORTA', 'pin': 'P31', 'pin_func': 'PA31_PWMR_OUT'}
	- {'name': 'PWM', 'idx': 0, 'func': 'CH8', 'port': 'PORTA', 'pin': 'P31', 'pin_func': 'PA31_PWM_CH8'}
	- {'name': 'UART', 'idx': '0', 'func': 'TX', 'port': 'PORTA', 'pin': 'P31', 'pin_func': 'PA31_UART0_TX'}
