mtb_version: 4
chip: pangu

diff:
  fota_version: 0
  ram_buf: 50         #DEC     KB   ( max ram need)
  flash_buf: 16       #DEC     KB   ( buffer size)
  flash_sector: 4096  #DEC     byte ( flash sector)
  diff_mode: 010      #BIN
  double_control: 1   #DEC (1--use 2 sector for diff restore,0--1 sector)
flash:
  base_address: 0x8000000       # 存储基地址，比如FLASH的基地址
  run_base_address: 0x18000000  # 运行基地址，一般指SDRAM的基地址
  sector: 4096       # Bytes
  size: 16777216      # $(sector count) * sector

partitions:
  - { name: bmtb,   address: 0x8000000, size: 0x001000 }
  - { name: boot,   address: 0x8001000, size: 0x020000 }
  - { name: tee,    address: 0x8021000, load_addr: 0x18000000, size: 0x010000 }
  - { name: imtb,   address: 0x8031000, size: 0x002000 }
  - { name: prim,   address: 0x8033000, load_addr: 0x18010000, size: 0x300000, verify: true, update: DIFF}
  - { name: cpu1,   address: 0x8333000, load_addr: 0x18500000, size: 0x080000, update: FULL }
  - { name: cpu2,   address: 0x83B3000, load_addr: 0x18600000, size: 0x200000, update: FULL }
  - { name: kv,     address: 0x8633000, size: 0x004000 }
  - { name: lpm,    address: 0x8637000, size: 0x020000 }
  - { name: misc,   address: 0x8657000, size: 0x400000 }
  - { name: kp,     address: 0x8FFF000, size: 0x001000 }

