
name: sdk_test_solutions
version: v7.4.3                                   
description: test_solutions SDK套件，包括各种依赖组件和test demo 
type: sdk

#tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
#license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

depends:
  # solutions
  - test_wifihal_api: v7.4.3
  - test_blehost_api: v7.4.3
  #- test_csi1: v7.4.3
  - test_csi2: v7.4.3
  - test_aoshal: v7.4.3
  - test_netmgr: v7.4.3
  - test_lwip: v7.4.3
  - test_fota: v7.4.3
  - test_mqtt: v7.4.3
  - test_wifiprovisioning: v7.4.3
  - test_kv: v7.4.3
  - test_blemesh_api: v7.4.3
  #- test_bootloader: v7.4.3
